#pragma once
#include "Strings_EN.h"

static const Strings STR_ES = {
    "Tester de Motor",
    "RPM:",
    "Velocidad:",
    "DIR:",
    "CW",
    "CCW",
    "FRENO:",
    "ON",
    "OFF",
    "ENABLE:",
    "LD:",
    "ALARM",
    "OK",
    "UP/DOWN: Vel.  SEL: Menu  MANTEN SEL: Atras/Arr-Det",
    "CONFIGURACION",
    "Arrancar",
    "Parar",
    "DIR = CCW",
    "DIR = CW",
    "Freno ON",
    "Freno OFF",
    "Seleccionar Motor",
    "Anadir Motor",
    "Borrar Activo",
    "Lenguaje/Telemetria",
    "Acerca de",
    "Atras",
    "UP/DOWN=Mover  SEL=Seleccionar",
    // Wizard
    "Nombre:",
    "Tiene FRENO?",
    "Tiene FG?",
    "Tiene LD?",
    "LD activo cuando:",
    "LOW",
    "HIGH",
    "Tiene STOP?",
    "STOP activo cuando:",
    "Tiene ENABLE?",
    "ENABLE activo:",
    "PPR (pulsos/vuelta)",
    "CLOCK max (Hz)",
    "Guardar perfil?",
    "SI",
    "NO",
    "UP/DOWN=Cambiar  SEL=Siguiente",
    "UP/DOWN=Mover  SEL=OK",
    "UP/DOWN=Cambiar  SEL=OK",
    "UP/DN=Car SEL=Sig/END",
    // Settings
    "CONFIGURACION",
    "Idioma",
    "English",
    "Espanol",
    "Telemetria",
    "Telemetria: ON",
    "Telemetria: OFF",
    // About
    "ACERCA DE",
    "Autor: Fran-Byte",
    "Version: v2.0",
    "Build:",
    // Diag
    "DIAGNOSTICO",
    "MANTEN SEL para salir"};
